version: '3.7'
services:
  ui:
    restart: always
    build:
      target: install
      context: .
      args:
        - NODE_VERSION=15.8.0
        - NODE_ENV=development
    command: npm run dev
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 8080:8080
    environment:
      - NODE_ENV=development
      - PORT=8080
